FROM ubuntu

WORKDIR /app

VOLUME /app/data

CMD ["bash"]




# sudo docker run -it --name container1 --privileged=true --volumes-from 6f889c2d7268 new1 /bin/bash --> to attach volume to another conatiner
 

